#!/bin/bash

# Handle ECR authentication errors with user-friendly guidance
# This script provides clear instructions when ECR authentication fails

echo "🚨 ECR Authentication Error Detected"
echo ""
echo "The webview service requires access to AWS ECR (Elastic Container Registry)."
echo "This error typically occurs when:"
echo ""
echo "1. 🔐 You haven't logged into AWS SSO"
echo "2. 🐳 Docker isn't authenticated with ECR"
echo "3. ⏰ Your authentication has expired"
echo ""
echo "🔧 Quick Fix Options:"
echo ""
echo "Option 1 - Full Authentication (Recommended):"
echo "   task ecr-login"
echo "   task up"
echo ""
echo "Option 2 - Start without webview (Backend development only):"
echo "   task up:no-webview"
echo ""
echo "Option 3 - Manual authentication:"
echo "   aws sso login --profile artifacts"
echo "   aws ecr get-login-password --profile artifacts --region eu-west-3 | \\"
echo "     docker login --username AWS --password-stdin 737968113546.dkr.ecr.eu-west-3.amazonaws.com"
echo "   task up"
echo ""
echo "💡 After authentication, you can access:"
echo "   - Webview (Frontend): http://localhost:8080"
echo "   - Backend API: http://localhost:3158"
echo ""
echo "❓ Need help with AWS setup? Check the README.md section 'Access to Powens Repository (ECR)'"